window.LANGUAGE_CATALOG = [
  { code: "af", name: "Afrikaans", native: "Afrikaans", speech: "af-ZA" },
  { code: "ar", name: "Arabic", native: "العربية", speech: "ar-SA" },
  { code: "hy", name: "Armenian", native: "Հայերեն", speech: "hy-AM" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycanca", speech: "az-AZ" },
  { code: "be", name: "Belarusian", native: "Беларуская", speech: "be-BY" },
  { code: "bs", name: "Bosnian", native: "Bosanski", speech: "bs-BA" },
  { code: "bg", name: "Bulgarian", native: "Български", speech: "bg-BG" },
  { code: "ca", name: "Catalan", native: "Català", speech: "ca-ES" },
  { code: "zh", name: "Chinese", native: "中文", speech: "zh-CN" },
  { code: "hr", name: "Croatian", native: "Hrvatski", speech: "hr-HR" },
  { code: "cs", name: "Czech", native: "Čeština", speech: "cs-CZ" },
  { code: "da", name: "Danish", native: "Dansk", speech: "da-DK" },
  { code: "nl", name: "Dutch", native: "Nederlands", speech: "nl-NL" },
  { code: "en", name: "English", native: "English", speech: "en-US" },
  { code: "et", name: "Estonian", native: "Eesti", speech: "et-EE" },
  { code: "fi", name: "Finnish", native: "Suomi", speech: "fi-FI" },
  { code: "fr", name: "French", native: "Français", speech: "fr-FR" },
  { code: "gl", name: "Galician", native: "Galego", speech: "gl-ES" },
  { code: "de", name: "German", native: "Deutsch", speech: "de-DE" },
  { code: "el", name: "Greek", native: "Ελληνικά", speech: "el-GR" },
  { code: "he", name: "Hebrew", native: "עברית", speech: "he-IL" },
  { code: "hi", name: "Hindi", native: "हिन्दी", speech: "hi-IN" },
  { code: "hu", name: "Hungarian", native: "Magyar", speech: "hu-HU" },
  { code: "is", name: "Icelandic", native: "Íslenska", speech: "is-IS" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia", speech: "id-ID" },
  { code: "it", name: "Italian", native: "Italiano", speech: "it-IT" },
  { code: "ja", name: "Japanese", native: "日本語", speech: "ja-JP" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", speech: "kn-IN" },
  { code: "kk", name: "Kazakh", native: "Қазақша", speech: "kk-KZ" },
  { code: "ko", name: "Korean", native: "한국어", speech: "ko-KR" },
  { code: "lv", name: "Latvian", native: "Latviešu", speech: "lv-LV" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių", speech: "lt-LT" },
  { code: "mk", name: "Macedonian", native: "Македонски", speech: "mk-MK" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu", speech: "ms-MY" },
  { code: "mi", name: "Maori", native: "Māori", speech: "mi-NZ" },
  { code: "mr", name: "Marathi", native: "मराठी", speech: "mr-IN" },
  { code: "ne", name: "Nepali", native: "नेपाली", speech: "ne-NP" },
  { code: "no", name: "Norwegian", native: "Norsk", speech: "nb-NO" },
  { code: "fa", name: "Persian", native: "فارسی", speech: "fa-IR" },
  { code: "pl", name: "Polish", native: "Polski", speech: "pl-PL" },
  { code: "pt", name: "Portuguese", native: "Português", speech: "pt-PT" },
  { code: "ro", name: "Romanian", native: "Română", speech: "ro-RO" },
  { code: "ru", name: "Russian", native: "Русский", speech: "ru-RU" },
  { code: "sr", name: "Serbian", native: "Српски", speech: "sr-RS" },
  { code: "sk", name: "Slovak", native: "Slovenčina", speech: "sk-SK" },
  { code: "sl", name: "Slovenian", native: "Slovenščina", speech: "sl-SI" },
  { code: "es", name: "Spanish", native: "Español", speech: "es-ES" },
  { code: "sw", name: "Swahili", native: "Kiswahili", speech: "sw-KE" },
  { code: "sv", name: "Swedish", native: "Svenska", speech: "sv-SE" },
  { code: "tl", name: "Tagalog", native: "Tagalog", speech: "fil-PH" },
  { code: "ta", name: "Tamil", native: "தமிழ்", speech: "ta-IN" },
  { code: "th", name: "Thai", native: "ไทย", speech: "th-TH" },
  { code: "tr", name: "Turkish", native: "Türkçe", speech: "tr-TR" },
  { code: "uk", name: "Ukrainian", native: "Українська", speech: "uk-UA" },
  { code: "ur", name: "Urdu", native: "اردو", speech: "ur-PK" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt", speech: "vi-VN" },
  { code: "cy", name: "Welsh", native: "Cymraeg", speech: "cy-GB" },
];

window.UI_TEXT = {
  ja: {
    documentTitle: "Annotator-Connotator",
    appName: "Annotator-Connotator",
    appTitle: "多言語アノテーション",
    inputText: "入力文",
    sourceLanguage: "入力言語",
    explanationLanguage: "解説言語",
    uiLanguage: "UI",
    autoDetect: "自動判定",
    difficulty: "難易度",
    beginner: "基礎",
    intermediate: "中級",
    advanced: "上級",
    academic: "学術",
    density: "抽出量",
    densityLow: "少なめ",
    densityStandard: "標準",
    densityHigh: "多め",
    focus: "観点",
    balanced: "バランス",
    speaking: "会話で使う",
    academicFocus: "論文・発表",
    grammarFocus: "構文",
    includeGrammar: "構文も拾う",
    includeSlash: "スラッシュ読み",
    analyze: "解析",
    analyzing: "解析中",
    sample: "例文",
    clear: "消去",
    textTab: "本文",
    wordsTab: "語句",
    readingTab: "読解",
    exportTab: "出力",
    speak: "音声再生",
    vocab: "語彙",
    expression: "表現",
    idiom: "イディオム",
    grammar: "構文",
    setting: "設定",
    translationTitle: "解説言語での翻訳",
    json: "JSON",
    markdown: "Markdown",
    close: "閉じる",
    serverKeyNeeded: ".env に OPENAI_API_KEY を入れると自動解析が使えます。",
    serverOffline: "app server に接続できていません。",
    modelReady: "Model: {model}",
    enterText: "入力文を入れてください。",
    analyzingStatus: "解析中...",
    extracted: "{count} 件の語句を抽出しました。",
    sampleLoaded: "例文を読み込みました。",
    cleared: "入力と結果を消去しました。",
    jsonCopied: "JSON をコピーしました。",
    markdownCopied: "Markdown をコピーしました。",
    speechUnsupported: "このブラウザは音声再生に対応していません。",
    emptyAnnotated: "解析するとここにハイライト付き本文が表示されます。",
    emptyWords: "語句リストはまだありません。",
    slashEmpty: "スラッシュ読みは未生成です。",
    translationEmpty: "翻訳はまだありません。",
    apiKeyRequired: ".env に OPENAI_API_KEY を入れてから server.js を再起動してください。",
    uiTranslating: "UIを翻訳中...",
    uiTranslationFailed: "UI翻訳に失敗しました。日本語表示に戻します。",
    examplePrefix: "例: ",
    sourceLanguageExport: "入力言語",
    explanationLanguageExport: "解説言語",
    uiLanguageExport: "UI言語",
  },
  en: {
    documentTitle: "Annotator-Connotator",
    appName: "Annotator-Connotator",
    appTitle: "Multilingual Annotation",
    inputText: "Input text",
    sourceLanguage: "Input language",
    explanationLanguage: "Explanation language",
    uiLanguage: "UI",
    autoDetect: "Auto-detect",
    difficulty: "Difficulty",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    academic: "Academic",
    density: "Density",
    densityLow: "Low",
    densityStandard: "Standard",
    densityHigh: "High",
    focus: "Focus",
    balanced: "Balanced",
    speaking: "Speaking",
    academicFocus: "Academic",
    grammarFocus: "Grammar",
    includeGrammar: "Include grammar",
    includeSlash: "Slash reading",
    analyze: "Analyze",
    analyzing: "Analyzing",
    sample: "Sample",
    clear: "Clear",
    textTab: "Text",
    wordsTab: "Items",
    readingTab: "Reading",
    exportTab: "Export",
    speak: "Play audio",
    vocab: "Vocab",
    expression: "Expressions",
    idiom: "Idioms",
    grammar: "Grammar",
    setting: "Setting",
    translationTitle: "Translation in explanation language",
    json: "JSON",
    markdown: "Markdown",
    close: "Close",
    serverKeyNeeded: "Add OPENAI_API_KEY to .env to enable automatic annotation.",
    serverOffline: "Cannot connect to the app server.",
    modelReady: "Model: {model}",
    enterText: "Please enter text.",
    analyzingStatus: "Analyzing...",
    extracted: "Extracted {count} items.",
    sampleLoaded: "Loaded the sample text.",
    cleared: "Cleared input and results.",
    jsonCopied: "Copied JSON.",
    markdownCopied: "Copied Markdown.",
    speechUnsupported: "This browser does not support speech playback.",
    emptyAnnotated: "Highlighted text will appear here after analysis.",
    emptyWords: "No items yet.",
    slashEmpty: "Slash reading has not been generated yet.",
    translationEmpty: "No translation yet.",
    apiKeyRequired: "Add OPENAI_API_KEY to .env, then restart server.js.",
    uiTranslating: "Translating UI...",
    uiTranslationFailed: "UI translation failed. Falling back to Japanese.",
    examplePrefix: "Example: ",
    sourceLanguageExport: "Source language",
    explanationLanguageExport: "Explanation language",
    uiLanguageExport: "UI language",
  },
};
