window.LANGUAGE_CATALOG = [
  { code: "af", name: "Afrikaans", native: "Afrikaans", speech: "af-ZA" },
  { code: "am", name: "Amharic", native: "አማርኛ", speech: "am-ET" },
  { code: "ar", name: "Arabic", native: "العربية", speech: "ar-SA" },
  { code: "hy", name: "Armenian", native: "Հայերեն", speech: "hy-AM" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycanca", speech: "az-AZ" },
  { code: "eu", name: "Basque", native: "Euskara", speech: "eu-ES" },
  { code: "be", name: "Belarusian", native: "Беларуская", speech: "be-BY" },
  { code: "bn", name: "Bengali", native: "বাংলা", speech: "bn-BD" },
  { code: "bs", name: "Bosnian", native: "Bosanski", speech: "bs-BA" },
  { code: "bg", name: "Bulgarian", native: "Български", speech: "bg-BG" },
  { code: "my", name: "Burmese", native: "မြန်မာဘာသာ", speech: "my-MM" },
  { code: "ca", name: "Catalan", native: "Català", speech: "ca-ES" },
  { code: "zh", name: "Chinese", native: "中文", speech: "zh-CN" },
  { code: "hr", name: "Croatian", native: "Hrvatski", speech: "hr-HR" },
  { code: "cs", name: "Czech", native: "Čeština", speech: "cs-CZ" },
  { code: "da", name: "Danish", native: "Dansk", speech: "da-DK" },
  { code: "nl", name: "Dutch", native: "Nederlands", speech: "nl-NL" },
  { code: "en", name: "English", native: "English", speech: "en-US" },
  { code: "et", name: "Estonian", native: "Eesti", speech: "et-EE" },
  { code: "fi", name: "Finnish", native: "Suomi", speech: "fi-FI" },
  { code: "fr", name: "French", native: "Français", speech: "fr-FR" },
  { code: "gl", name: "Galician", native: "Galego", speech: "gl-ES" },
  { code: "ka", name: "Georgian", native: "ქართული", speech: "ka-GE" },
  { code: "de", name: "German", native: "Deutsch", speech: "de-DE" },
  { code: "el", name: "Greek", native: "Ελληνικά", speech: "el-GR" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", speech: "gu-IN" },
  { code: "ha", name: "Hausa", native: "Hausa", speech: "ha-NG" },
  { code: "he", name: "Hebrew", native: "עברית", speech: "he-IL" },
  { code: "hi", name: "Hindi", native: "हिन्दी", speech: "hi-IN" },
  { code: "hu", name: "Hungarian", native: "Magyar", speech: "hu-HU" },
  { code: "is", name: "Icelandic", native: "Íslenska", speech: "is-IS" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia", speech: "id-ID" },
  { code: "it", name: "Italian", native: "Italiano", speech: "it-IT" },
  { code: "ja", name: "Japanese", native: "日本語", speech: "ja-JP" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", speech: "kn-IN" },
  { code: "kk", name: "Kazakh", native: "Қазақша", speech: "kk-KZ" },
  { code: "km", name: "Khmer", native: "ខ្មែរ", speech: "km-KH" },
  { code: "ko", name: "Korean", native: "한국어", speech: "ko-KR" },
  { code: "lo", name: "Lao", native: "ລາວ", speech: "lo-LA" },
  { code: "lv", name: "Latvian", native: "Latviešu", speech: "lv-LV" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių", speech: "lt-LT" },
  { code: "mk", name: "Macedonian", native: "Македонски", speech: "mk-MK" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu", speech: "ms-MY" },
  { code: "ml", name: "Malayalam", native: "മലയാളം", speech: "ml-IN" },
  { code: "mt", name: "Maltese", native: "Malti", speech: "mt-MT" },
  { code: "mr", name: "Marathi", native: "मराठी", speech: "mr-IN" },
  { code: "ne", name: "Nepali", native: "नेपाली", speech: "ne-NP" },
  { code: "no", name: "Norwegian", native: "Norsk", speech: "nb-NO" },
  { code: "fa", name: "Persian", native: "فارسی", speech: "fa-IR" },
  { code: "pl", name: "Polish", native: "Polski", speech: "pl-PL" },
  { code: "pt", name: "Portuguese", native: "Português", speech: "pt-PT" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ", speech: "pa-IN" },
  { code: "ro", name: "Romanian", native: "Română", speech: "ro-RO" },
  { code: "ru", name: "Russian", native: "Русский", speech: "ru-RU" },
  { code: "sr", name: "Serbian", native: "Српски", speech: "sr-RS" },
  { code: "sk", name: "Slovak", native: "Slovenčina", speech: "sk-SK" },
  { code: "sl", name: "Slovenian", native: "Slovenščina", speech: "sl-SI" },
  { code: "es", name: "Spanish", native: "Español", speech: "es-ES" },
  { code: "sw", name: "Swahili", native: "Kiswahili", speech: "sw-KE" },
  { code: "sv", name: "Swedish", native: "Svenska", speech: "sv-SE" },
  { code: "tl", name: "Tagalog", native: "Tagalog", speech: "fil-PH" },
  { code: "ta", name: "Tamil", native: "தமிழ்", speech: "ta-IN" },
  { code: "te", name: "Telugu", native: "తెలుగు", speech: "te-IN" },
  { code: "th", name: "Thai", native: "ไทย", speech: "th-TH" },
  { code: "tr", name: "Turkish", native: "Türkçe", speech: "tr-TR" },
  { code: "uk", name: "Ukrainian", native: "Українська", speech: "uk-UA" },
  { code: "uz", name: "Uzbek", native: "Oʻzbekcha", speech: "uz-UZ" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt", speech: "vi-VN" },
  { code: "cy", name: "Welsh", native: "Cymraeg", speech: "cy-GB" },
  { code: "yo", name: "Yoruba", native: "Yorùbá", speech: "yo-NG" },
  { code: "zu", name: "Zulu", native: "isiZulu", speech: "zu-ZA" },
];

window.UI_TEXT = {
  ja: {
    documentTitle: "Annotator-Connotator",
    appName: "Annotator-Connotator",
    appTitle: "多言語アノテーション",
    inputText: "入力文",
    textInputMode: "文章",
    youtubeInputMode: "YouTube",
    youtubeUrl: "YouTube URL",
    youtubeImport: "字幕を取得",
    youtubeImporting: "取得中",
    correctTranscript: "音声認識ミスをAIで補正",
    captionAuto: "自動字幕",
    captionManual: "手動字幕",
    sourceLanguage: "入力言語",
    explanationLanguage: "解説言語",
    uiLanguage: "UI",
    autoDetect: "自動判定",
    difficulty: "難易度",
    beginner: "基礎",
    intermediate: "中級",
    advanced: "上級",
    analysisMode: "解析モード",
    standardAnalysis: "通常（Luna）",
    preciseAnalysis: "精密（Sol）",
    density: "抽出量",
    densityLow: "少なめ",
    densityStandard: "標準",
    densityHigh: "多め",
    nuanceDetail: "ニュアンス表示",
    nuanceLow: "少なめ",
    nuanceStandard: "標準",
    nuanceHigh: "詳しく",
    nuance: "ニュアンス",
    primaryCategory: "主",
    secondaryCategory: "副",
    focus: "観点",
    allFocus: "すべて",
    speaking: "会話で使う",
    academicFocus: "論文・発表",
    includeGrammar: "構文も拾う",
    includeSlash: "スラッシュ読み",
    includeTranslation: "翻訳を表示",
    analyze: "解析",
    analyzing: "解析中",
    cancelAnalysis: "中止",
    sample: "サンプル",
    clear: "消去",
    textTab: "本文",
    wordsTab: "語句",
    readingTab: "読解",
    exportTab: "出力",
    speak: "音声再生",
    vocab: "単語・専門語",
    expression: "連語・定型表現",
    wordType: "単語",
    collocationType: "連語",
    formulaType: "定型表現",
    constructionType: "構文",
    idiom: "慣用表現",
    termType: "専門語",
    grammar: "構文",
    setting: "設定",
    translationTitle: "解説言語での翻訳",
    json: "JSON",
    markdown: "Markdown",
    close: "閉じる",
    serverKeyNeeded: ".env に OPENAI_API_KEY を入れると自動解析が使えます。",
    serverOffline: "app server に接続できていません。",
    modelReady: "Model: {model}",
    modelsReady: "通常: {standard} / 精密: {precise}",
    enterText: "入力文を入れてください。",
    youtubeUrlRequired: "YouTubeのURLを入力してください。",
    youtubeImportStatus: "YouTube字幕を取得しています...",
    youtubeImported: "{title}：{chars}文字の字幕を取り込みました。{correction}",
    youtubeCorrectionApplied: "AI補正済みです。",
    youtubeCorrectionSkipped: "字幕原文のままです。",
    youtubeCorrectionFailed: "AI補正には失敗したため、字幕原文を取り込みました。",
    youtubeNoCaptions: "この動画には利用できる字幕がありません。",
    youtubeBlocked: "YouTube側で字幕取得が制限されました。時間を置くか、VPNを切って再試行してください。",
    youtubeUnavailable: "動画が非公開・削除済み・年齢制限付き、または利用できません。",
    youtubeImportFailed: "YouTube字幕を取得できませんでした。",
    analyzingStatus: "解析中...",
    analyzingChunk: "セクション {current} / {total} を解析中...",
    mergingSections: "解析結果をまとめています...",
    analysisCancelling: "解析を中止しています...",
    analysisCancelled: "解析を中止しました。前の結果はそのまま残っています。",
    analysisPartialFailure: "{total}セクション中{completed}セクションまで完了しましたが、途中で失敗しました。前の結果は変更していません。",
    extracted: "{count} 件の語句と {nuances} 件のニュアンスを抽出しました。",
    sampleLoaded: "例文を読み込みました。",
    cleared: "入力と結果を消去しました。",
    jsonCopied: "JSON をコピーしました。",
    markdownCopied: "Markdown をコピーしました。",
    speechUnsupported: "このブラウザは音声再生に対応していません。",
    emptyAnnotated: "解析するとここにハイライト付き本文が表示されます。",
    emptyWords: "語句リストはまだありません。",
    slashEmpty: "スラッシュ読みは未生成です。",
    translationEmpty: "翻訳はまだありません。",
    apiKeyRequired: ".env に OPENAI_API_KEY を入れてから server.js を再起動してください。",
    uiTranslating: "UIを翻訳中...",
    uiTranslationFailed: "UI翻訳に失敗しました。日本語表示に戻します。",
    examplePrefix: "例: ",
    patternLabel: "型",
    nuanceSurface: "語義",
    nuanceSuggested: "コノテーション",
    nuanceEffect: "この文脈での働き",
    nuanceContext: "注意・別の読み方",
    nuanceAlternatives: "別の解釈",
    nuanceEvidence: "根拠",
    nuanceConfidence: "確信度",
    nuanceConventionality: "成立のしかた",
    confidenceHigh: "高",
    confidenceMedium: "中",
    confidenceLow: "低",
    conventional: "慣習的",
    contextual: "文脈依存",
    mixed: "慣習＋文脈",
    categoryGlossaryLabel: "ニュアンスカテゴリ。各ラベルに説明があります",
    categoryGlossaryOpen: "ニュアンスカテゴリの説明",
    categoryGlossaryTitle: "ニュアンスカテゴリ",
    categoryHelpEvaluative: "対象を良い・悪い、魅力的・不快などと捉えるニュアンス",
    categoryHelpStance: "話し手が内容や対象に対して示す態度・立場",
    categoryHelpPoliteness: "相手への配慮、親しさ、距離、上下関係の示し方",
    categoryHelpImplicature: "明言されていないが、文脈から推論される意味",
    categoryHelpPresupposition: "発話の前提として共有済み・当然と扱われる情報",
    categoryHelpRegister: "場面、媒体、社会関係に応じた言葉づかいの違い",
    categoryHelpIrony: "表面とは異なる評価を伝える皮肉・反語",
    categoryHelpEuphemism: "直接的な表現を避けて和らげる言い方",
    evaluative: "評価",
    stance: "スタンス",
    politeness: "ポライトネス",
    implicature: "含意",
    presupposition: "前提",
    register: "レジスター",
    irony: "皮肉",
    euphemism: "婉曲",
    noNuances: "根拠のあるニュアンスは検出されませんでした。",
    sourceLanguageExport: "入力言語",
    explanationLanguageExport: "解説言語",
    uiLanguageExport: "UI言語",
  },
  en: {
    documentTitle: "Annotator-Connotator",
    appName: "Annotator-Connotator",
    appTitle: "Multilingual Annotation",
    inputText: "Input text",
    textInputMode: "Text",
    youtubeInputMode: "YouTube",
    youtubeUrl: "YouTube URL",
    youtubeImport: "Get captions",
    youtubeImporting: "Loading",
    correctTranscript: "Correct speech-recognition errors with AI",
    captionAuto: "Auto-generated captions",
    captionManual: "Manual captions",
    sourceLanguage: "Input language",
    explanationLanguage: "Explanation language",
    uiLanguage: "UI",
    autoDetect: "Auto-detect",
    difficulty: "Difficulty",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    analysisMode: "Analysis mode",
    standardAnalysis: "Standard (Luna)",
    preciseAnalysis: "Precise (Sol)",
    density: "Density",
    densityLow: "Low",
    densityStandard: "Standard",
    densityHigh: "High",
    nuanceDetail: "Nuance detail",
    nuanceLow: "Brief",
    nuanceStandard: "Standard",
    nuanceHigh: "Detailed",
    nuance: "Nuance",
    primaryCategory: "Primary",
    secondaryCategory: "Secondary",
    focus: "Focus",
    allFocus: "All",
    speaking: "Speaking",
    academicFocus: "Academic",
    includeGrammar: "Include grammar",
    includeSlash: "Slash reading",
    includeTranslation: "Show translation",
    analyze: "Analyze",
    analyzing: "Analyzing",
    cancelAnalysis: "Cancel",
    sample: "Sample",
    clear: "Clear",
    textTab: "Text",
    wordsTab: "Items",
    readingTab: "Reading",
    exportTab: "Export",
    speak: "Play audio",
    vocab: "Words & terms",
    expression: "Collocations & formulas",
    wordType: "Word",
    collocationType: "Collocation",
    formulaType: "Formula",
    constructionType: "Construction",
    idiom: "Idioms",
    termType: "Technical term",
    grammar: "Grammar",
    setting: "Setting",
    translationTitle: "Translation in explanation language",
    json: "JSON",
    markdown: "Markdown",
    close: "Close",
    serverKeyNeeded: "Add OPENAI_API_KEY to .env to enable automatic annotation.",
    serverOffline: "Cannot connect to the app server.",
    modelReady: "Model: {model}",
    modelsReady: "Standard: {standard} / Precise: {precise}",
    enterText: "Please enter text.",
    youtubeUrlRequired: "Enter a YouTube URL.",
    youtubeImportStatus: "Fetching YouTube captions...",
    youtubeImported: "{title}: imported {chars} characters of captions. {correction}",
    youtubeCorrectionApplied: "AI correction applied.",
    youtubeCorrectionSkipped: "Imported the original captions.",
    youtubeCorrectionFailed: "AI correction failed, so the original captions were imported.",
    youtubeNoCaptions: "No usable captions are available for this video.",
    youtubeBlocked: "YouTube blocked the caption request. Try again later or turn off your VPN.",
    youtubeUnavailable: "The video is private, deleted, age-restricted, or unavailable.",
    youtubeImportFailed: "Could not fetch the YouTube captions.",
    analyzingStatus: "Analyzing...",
    analyzingChunk: "Analyzing section {current} / {total}...",
    mergingSections: "Combining analysis results...",
    analysisCancelling: "Cancelling analysis...",
    analysisCancelled: "Analysis cancelled. The previous result is unchanged.",
    analysisPartialFailure: "Completed {completed} of {total} sections before a failure. The previous result is unchanged.",
    extracted: "Extracted {count} items and {nuances} nuances.",
    sampleLoaded: "Loaded the sample text.",
    cleared: "Cleared input and results.",
    jsonCopied: "Copied JSON.",
    markdownCopied: "Copied Markdown.",
    speechUnsupported: "This browser does not support speech playback.",
    emptyAnnotated: "Highlighted text will appear here after analysis.",
    emptyWords: "No items yet.",
    slashEmpty: "Slash reading has not been generated yet.",
    translationEmpty: "No translation yet.",
    apiKeyRequired: "Add OPENAI_API_KEY to .env, then restart server.js.",
    uiTranslating: "Translating UI...",
    uiTranslationFailed: "UI translation failed. Falling back to Japanese.",
    examplePrefix: "Example: ",
    patternLabel: "Pattern",
    nuanceSurface: "Gloss",
    nuanceSuggested: "Connotation",
    nuanceEffect: "Effect in this context",
    nuanceContext: "Context and other readings",
    nuanceAlternatives: "Alternatives",
    nuanceEvidence: "Evidence",
    nuanceConfidence: "Confidence",
    nuanceConventionality: "Source of nuance",
    confidenceHigh: "High",
    confidenceMedium: "Medium",
    confidenceLow: "Low",
    conventional: "Conventional",
    contextual: "Contextual",
    mixed: "Conventional + contextual",
    categoryGlossaryLabel: "Connotation categories; each label has a description",
    categoryGlossaryOpen: "Explain connotation categories",
    categoryGlossaryTitle: "Connotation categories",
    categoryHelpEvaluative: "How the wording presents something as good, bad, appealing, unpleasant, or otherwise valued",
    categoryHelpStance: "The speaker's attitude or position toward the content or its subject",
    categoryHelpPoliteness: "How wording manages consideration, solidarity, distance, or social position",
    categoryHelpImplicature: "Meaning inferred from context even though it is not stated directly",
    categoryHelpPresupposition: "Information treated as already shared, expected, or taken for granted",
    categoryHelpRegister: "Wording associated with a setting, medium, community, or social relationship",
    categoryHelpIrony: "Wording that conveys an evaluation different from its surface presentation",
    categoryHelpEuphemism: "Indirect wording that softens a more direct expression",
    evaluative: "Evaluation",
    stance: "Stance",
    politeness: "Politeness & distance",
    implicature: "Implicature",
    presupposition: "Presupposition & expectation",
    register: "Register",
    irony: "Irony",
    euphemism: "Euphemism",
    noNuances: "No grounded nuance was detected.",
    sourceLanguageExport: "Source language",
    explanationLanguageExport: "Explanation language",
    uiLanguageExport: "UI language",
  },
};
